### ISSUE TITLE
Chinese file names cannot be downloaded. 

### ISSUE THREAD

**Issue by lufuhu** [rndme/download#112] opened 2022-05-13 02:44 UTC
```
 download(encodeURI(dataUrl))
```

**Comment by rndme** [comment] 2023-05-30 06:15
Cannot reproduce, closing. In general, if you have trouble with the argument overloads, passing all 3 arguments in order should side-step some edge cases in the arity auto-detection.

**Closed as completed by rndme** 2023-05-30 06:15 UTC
