### ISSUE TITLE
Support download of MS Office docx and xlsx files

### ISSUE THREAD

**Issue by brightrain** [rndme/download#21] opened 2016-04-07 20:40 UTC
Thank you for this great resource. I'm using it to download files returned from a request that uses a proxy and the link to the documents cannot simply be placed in an `<a href>`

I can successfully download all file types with the exception of the microsoft office `docx` and `xlsx` types. When attempting to open the downloaded files with MS Office I get an error message stating that they are corrupt and cannot be repaired.

I have tried including the correct mime type
`application/vnd.openxmlformats-officedocument.wordprocessingml.document`

AND

leaving the mime type blank (and[ defaulting to `application/octet-stream`](https://github.com/rndme/download/blob/master/download.js#L29))

Both result in corrupted file.

Any ideas how to support the download of those file types correctly?

my code:
```
var x = new XMLHttpRequest();
 x.open("GET", attachUrl, true);
 x.responseType = 'blob';
// with correct mime type
//x.onload = function (e) { download(x.response, name, file.ContentType); }
// without mime type
x.onload = function (e) { download(x.response, name); }
console.log(file.ContentType);
x.send();
```

and the error message in MS Office
![corrupt](https://cloud.githubusercontent.com/assets/1395985/14366146/8d2895ac-fcce-11e5-95a4-763ef5b8b37b.png)

**Comment by rndme** [comment] 2016-04-08 20:27
yikes: this is the 2nd issue with office in as many days. other binary files seem to have no issue. i'll look into it and see if there's something we can do to fix it. Thanks for dropping me a line and for being so thorough in the problem description (psychically pre-answering follow-ups).

**Comment by brightrain** [comment] 2016-04-08 21:25
Yes, I can successfully download Office `xls` and `doc` as well as `pdf` and image formats `png`, `jpg` and `gif`.

Thanks for looking into this and I'll do some more testing on my side to see if I can come up with anything.

:8ball: and definitely psychic : )

**Comment by rndme** [comment] 2016-04-08 22:26
thanks for your time and efforts.

i wasn't able to reproduce the issue. i'm guessing that it might be non-ascii chars getting mis-encoded because the web document that's doing the downloading's charset conflicts with the file or serving encoding, but i'm have trouble replicating. i only have office2010, and i can't seem to make a file that's a problem. 

It would be a **huge ** help if you could find/make a small doc that has the problem because without something to put under the microscope, it's hard to find the disease...

not sure if you post public files here, so i made a one-off private uploader at http://pagedemos.com/delmetemp/ where you can send me a zip, or both files with a refresh. just files, nothing fancy and explanations not needed, i'll figure it out. i'll pull that link down when i get the files and i won't share the contents with anyone.

if that's too much, can you just let me know if the file size of the orig and copy exactly matched?

**Comment by brightrain** [comment] 2016-04-11 17:34
Sure, it's the least I can do. I created a `docx` and `xlsx` file in MS Office 2013, uploaded them thru my app and then downloaded them again to reproduce the issue. Both are reported to be corrupt when attempting to open them with the same MS Office 2013 apps that created them.

Got an error trying to upload them here but you can grab them here:
https://www.dropbox.com/s/sl2qwnxuzxyqv0e/download-test.docx?dl=0

https://www.dropbox.com/s/auysstkkksxecn6/download-test.xlsx?dl=0

**Comment by rndme** [comment] 2016-04-13 06:26
thanks a million. I'm getting swamped ATM, but this should help a bunch when i get a chance to dig in.

**Comment by brightrain** [comment] 2016-04-13 20:57
You bet. Let me know if I can provide anything more here.

**Comment by fnicollet** [comment] 2016-05-26 15:01
Hello,

Ran into a similar issue and found the issue was somehow surprising. There is a regex to check if the file is a dataUrl or not:
https://github.com/rndme/download/blob/master/download.js#L64

And well, it fails when the mimetype has a "-" in it, as in ms-excel or ms-*. So it works for images, pdf, zip and all that but because of that error, download.js thought it was a simple URL and would crash.

I changed the regex to 
```
if(/^data\:[\w+[,;]/.test(payload)){
```
and it fixed my issue. Might help @brightrain 

Fabien

**Comment by rndme** [comment] 2016-05-30 00:54
@fnicollet : aha! that makes sense. i want to keep the left-side of the mime tighter, but you made me realize that the right side needs to allow dots. this long-standing problem was fixed with a one-char commit: https://github.com/rndme/download/commit/70f7701fe395c4c65b803894cee976d97935f513 (ok, two chars for readability, but still...)

thanks again!

**Closed by rndme** 2016-05-30 00:54 UTC

**Comment by brightrain** [comment] 2016-06-01 17:53
:+1: This resolved the issue. Much appreciated.
